# Generated by Django 3.0.4 on 2020-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_auto_20200408_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredProvider',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='submittedplace',
            name='preferred_provided',
            field=models.TextField(blank=True, null=True),
        ),
    ]
