version: '3.7'
services:
  postgres:
      ports:
        - "5432:5432"
      image: postgis/postgis
      volumes:
        - ../../postgres-data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_PASSWORD=supp0rtl0cal
        - POSTGRES_USER=supportlocal
